//物质融合铜类标签
ServerEvents.tags('item', event => {
    event.add('extreme_hardcore:copper', 'minecraft:copper_block')
    event.add('extreme_hardcore:copper', 'minecraft:cut_copper')
    event.add('extreme_hardcore:copper', 'minecraft:exposed_copper')
    event.add('extreme_hardcore:copper', 'minecraft:exposed_cut_copper')
    event.add('extreme_hardcore:copper', 'minecraft:weathered_copper')
    event.add('extreme_hardcore:copper', 'minecraft:weathered_cut_copper')
    event.add('extreme_hardcore:copper', 'minecraft:oxidized_copper')
    event.add('extreme_hardcore:copper', 'minecraft:oxidized_cut_copper')
    event.add('extreme_hardcore:copper', 'minecraft:waxed_copper_block')
    event.add('extreme_hardcore:copper', 'minecraft:waxed_cut_copper')
    event.add('extreme_hardcore:copper', 'minecraft:waxed_exposed_copper')
    event.add('extreme_hardcore:copper', 'minecraft:waxed_exposed_cut_copper')
    event.add('extreme_hardcore:copper', 'minecraft:waxed_weathered_copper')
    event.add('extreme_hardcore:copper', 'minecraft:waxed_weathered_cut_copper')
    event.add('extreme_hardcore:copper', 'minecraft:waxed_oxidized_copper')
    event.add('extreme_hardcore:copper', 'minecraft:waxed_oxidized_cut_copper')
})