//物质融合冰类标签
ServerEvents.tags('item', event => {
    event.add('extreme_hardcore:ice', 'minecraft:ice')
    event.add('extreme_hardcore:ice', 'minecraft:packed_ice')
    event.add('extreme_hardcore:ice', 'minecraft:blue_ice')
    event.add('extreme_hardcore:ice', 'minecraft:snowball')
    event.add('extreme_hardcore:ice', 'minecraft:snow_block')
    event.add('extreme_hardcore:ice', 'minecraft:water_bucket')
    event.add('extreme_hardcore:ice', 'minecraft:cod_bucket')
    event.add('extreme_hardcore:ice', 'minecraft:salmon_bucket')
    event.add('extreme_hardcore:ice', 'minecraft:tropical_fish_bucket')
    event.add('extreme_hardcore:ice', 'minecraft:pufferfish_bucket')
    event.add('extreme_hardcore:ice', 'minecraft:axolotl_bucket')
    event.add('extreme_hardcore:ice', 'minecraft:tadpole_bucket')
})