//物质融合特殊物质标签
ServerEvents.tags('item', event => {
    event.add('extreme_hardcore:special', 'minecraft:sculk_catalyst')
    event.add('extreme_hardcore:special', 'minecraft:bedrock')
    event.add('extreme_hardcore:special', 'minecraft:cobweb')
    event.add('extreme_hardcore:special', 'minecraft:suspicious_sand')
    event.add('extreme_hardcore:special', 'minecraft:suspicious_gravel')
    event.add('extreme_hardcore:special', 'minecraft:bee_nest')
    event.add('extreme_hardcore:special', 'minecraft:end_crystal')
    event.add('extreme_hardcore:special', 'minecraft:respawn_anchor')
    event.add('extreme_hardcore:special', 'minecraft:ender_eye')
    event.add('extreme_hardcore:special', 'minecraft:fire_charge')
    event.add('extreme_hardcore:special', 'realistictorches:matchbox')
    event.add('extreme_hardcore:special', 'minecraft:torch')
    event.add('extreme_hardcore:special', 'minecraft:soul_torch')
    event.add('extreme_hardcore:special', 'minecraft:redstone_torch')
    event.add('extreme_hardcore:special', 'realistictorches:lit_torch')
    event.add('extreme_hardcore:special', 'minecraft:end_rod')
    event.add('extreme_hardcore:special', 'minecraft:totem_of_undying')
    event.add('extreme_hardcore:special', 'minecraft:tnt')
    event.add('extreme_hardcore:special', 'minecraft:echo_shard')
    event.add('extreme_hardcore:special', 'minecraft:experience_bottle')
    event.add('extreme_hardcore:special', 'thinair:soulfire_bottle')
})