"Enable bounce blue wither skull" = true
"Enable more inertial blue wither skull" = true
"Enable shoot more blue wither skull" = false
"Enable spin and white summon" = true
"Enable explode by half health" = false
"Enable explode by die" = true
"Enable charge attack" = true
"Enable maintain weakened state" = true

